apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
        env: development
    spec:
      containers:
      - name: my-app
        image: ismailfakir/helloworld:firsttry
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "4000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 8080
    protocol: TCP
  selector:
    app: my-app